spring:
    datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:tcp://localhost/~/kotlin
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true